# --- General Settings ---
 logging:
   level: INFO
   format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
   log_file: "var/logs/app.log"

 # --- Repository Indexing Settings ---
 repository:
   # Path to the root of the repository to be scanned.
   # Can be overridden by CLI argument.
   root_path: "/Users/chamath/demo/repositories/abc-service" # Example path, adjust as needed

 indexing:
   source_roots: [ "src/main/kotlin" ]
   test_roots: [ "src/test/kotlin" ]
   code_extensions: [ ".kt" ]
   ignore_patterns:
     - ".git/"
     - ".github/"
     - ".gradle/"
     - ".kotlin/"
     - "build/"
     - "deployments/"
     - "gradle/wrapper/"
     - "var/" # Assuming our tool's output/temp data goes here
     - "**/resources/"
     - "**/proto/"
     - "**/migration/scripts/"
     - "*.sh"
     - "*.bat"
     - "*.md"
     - "*.yml"
     - "*.yaml"
     - "*.json"
     - "*.sql"
     - "*.xml"
     - "*.csv"
     - "*.jar"
     - "*.properties"
     - ".editorconfig"
     - ".gitattributes"
     - ".gitignore"
     - ".gitleaksignore"
     - ".trivyignore"
     - ".prd-deploy-protect"
     - "Dockerfile"
     - "settings.gradle.kts"
     - "build.gradle.kts"
     - "gradle.properties"
     - "detekt.yml"

   # Path where the generated index file will be stored (relative to project root)
   index_file_path: "var/index/repository_index.json"
   # Naming conventions for linking source to tests
   # {ClassName} -> {ClassName}Test
   test_suffixes: ["Test"]
   test_prefixes: []

 # --- Embedding Settings (Placeholder for now) ---
 embedding:
   provider: "sentence_transformer" # or "openai"
   model_name: "all-MiniLM-L6-v2"
   # api_key: ${OPENAI_API_KEY} # Example for OpenAI

 # --- Vector DB Settings (Placeholder for now) ---
 vector_db:
   provider: "chroma" # or "pinecone"
   path: "var/rag_db/chroma" # For ChromaDB
   collection_name: "code_artifacts"
   # api_key: ${PINECONE_API_KEY} # Example for Pinecone
   # environment: "us-west1-gcp" # Example for Pinecone
   distance_metric: "cosine"

 # --- Test Generation Settings (Placeholder for now) ---
 generation:
   output_dir: "generated-tests"
   llm_provider: "mock" # or "openai", "anthropic"
   # model_name: "gpt-4-turbo-preview"
   # api_key: ${OPENAI_API_KEY}
   context_max_similar_files: 2